/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8f6a5c9c-edec-4c48-b3ea-faf42c833005",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "3e3361e64b7440efb5f60659c2ef8c9d",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
